[package]
name = "warden"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
homepage = "https://git.kanjala.com/warden"
documentation = "https://books.kanjala.com/warden"
description = "A rule-based fraud detection platform"

[dependencies]
