[workspace]
resolver = "3"
members = ["crates/*", "lib/*"]

[workspace.package]
license = "AGPL-3.0-only"
homepage = "https://git.kanjala.com/warden"
documentation = "https://books.kanjala.com/warden"
description = "A rule-based fraud detection platform"

[workspace.dependencies]
warden-core = { path = "lib/warden-core" }
