[application]
environment = "development"
port = 2210

[cache]
dsn = [ "redis://localhost:6379" ]
cluster = false

[nats]
hosts = ["nats://localhost:4222"]

[nats.pub_subjects]
transaction_history = "transaction_history.add"
accounts = "pseudonyms.accounts.add"

# vim:ft=toml

