permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: check
jobs:
  dockerfile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        crate:
          - pseudonyms
          - warden
          - configuration
          - router
          - rule-executor
          - aggregator
    name: dockerfile / ${{ matrix.crate }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: build # and push
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: crates/${{ matrix.crate }}/Dockerfile
          tags: warden/${{ matrix.crate }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  msrv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        msrv: ["1.89.0"]
    name: msrv / ${{ matrix.msrv }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Install ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.msrv }}
      - name: install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: cargo install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: cargo hack +${{ matrix.msrv }} 
        run: cargo hack --clean-per-run --feature-powerset check
