permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: dockerfile
jobs:
  pseudonyms:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        crate: ["pseudonyms", "warden", "configuration", "router"]
    name: build / ${{ matrix.crate }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: build # and push
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: crates/${{ matrix.crate }}/Dockerfile
          tags: warden/${{ matrix.crate }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
